# Generated by Django 5.2.4 on 2025-09-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='definition',
            field=models.TextField(max_length=1000),
        ),
    ]
