# Generated by Django 5.2.4 on 2026-01-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_flashcard_definition'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_changed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
